Fix broken link and add author info in extension.json
miraheze/MessageCachePerformance pull request #2
Opened 2024-06-28 01:32 UTC by colleirose

2024-06-28 21:47 UTC, OAuthority commented on extension.json
> +		"Miraheze",
Universal Omega and Paladox are the only ones who have contributed to this and they are already listed, so I don't think its necessary to also list Miraheze.

2024-06-28 23:17 UTC, colleirose commented on extension.json
> +		"Miraheze",
Fixed.

2024-09-21 23:50 UTC, Universal-Omega requested changes

2024-09-21 23:50 UTC, Universal-Omega commented on extension.json
> +		"Paladox",
Invalkd json, you can't have a trailing comma

2024-09-22 04:59 UTC, merged